-- =====================================================================
-- Aba "Contingency Atual" — mesma lógica da "Forecast Atual", só que pro
-- arquivo de Contingency (mesmo layout de ~85 colunas por posição relativa
-- à coluna "Process" — ver comentário em forecast_atual acima). Upload
-- confirmado APAGA a tabela inteira e insere de novo — só existe o mês
-- mais recente, nunca histórico.
-- Rodar uma vez no SQL editor do Supabase do projeto (rpibvjcnrseuugpkfmdj
-- não — este é o projeto sydamnqagkdmczmgkvso, "Comunicações Bridgestone").
-- =====================================================================
drop table if exists contingency_atual;
create table contingency_atual (
  processo text primary key,
  escritorio text,
  assessed_status text,
  status_processo text,
  data_distribuicao text,
  data_ajuizamento text,
  data_encerramento text,
  rl text,
  centro_custo text,
  data_admissao text,
  data_demissao text,
  cargo text,
  tipo_salario text,
  departamento_1 text,
  departamento_2 text,
  business text,
  tipo_caso text,
  revised text,
  forecast_grupo text,
  cidade text,
  uf text,
  reclamante text,
  cpf_reclamante text,
  advogado_reclamante text,
  reclamada text,
  terceirizacao text,
  empresa text,
  empresa_status text,
  fase_atual text,
  fase_atual_divisao text,
  historico_percentual_atual numeric,
  historico_atual numeric,
  correcao_atual numeric,
  correcao_percentual_atual numeric,
  juros_atual numeric,
  juros_percentual_atual numeric,
  provisao_atual numeric,
  correcao_juros_percentual_atual numeric,
  total_possivel_atual numeric,
  total_remoto_atual numeric,
  accrual_atual numeric,
  fase_anterior text,
  fase_anterior_divisao text,
  historico_percentual_anterior numeric,
  historico_anterior numeric,
  correcao_anterior numeric,
  correcao_percentual_anterior numeric,
  juros_anterior numeric,
  juros_percentual_anterior numeric,
  provisao_anterior numeric,
  correcao_juros_percentual_anterior numeric,
  total_possivel_anterior numeric,
  total_remoto_anterior numeric,
  accrual_anterior numeric,
  diferenca_accrual numeric,
  diferenca_juros_correcao numeric,
  diferenca_historico numeric,
  mudanca_fase text,
  mudanca_fase_detalhe text,
  ajuste text,
  pagamentos_liberacao_depositos numeric,
  pagamento_historico_inss_honorarios_ir numeric,
  baixa_recursal_pagamento numeric,
  deposito_garantia_valor numeric,
  deposito_garantia_data text,
  deposito_garantia_disposicao_1 text,
  deposito_garantia_disposicao_2 text,
  deposito_garantia_comparativo text,
  deposito_garantia_reclamante numeric,
  deposito_garantia_reclamada numeric,
  deposito_pagamento_valor numeric,
  deposito_pagamento_data text,
  deposito_pagamento_disposicao_1 text,
  deposito_pagamento_disposicao_2 text,
  deposito_pagamento_comparativo text,
  deposito_pagamento_reclamante numeric,
  deposito_pagamento_reclamada numeric,
  deposito_recursal_valor numeric,
  deposito_recursal_disposicao_1 text,
  deposito_recursal_disposicao_2 text,
  deposito_recursal_comparativo text,
  deposito_recursal_reclamante numeric,
  deposito_recursal_reclamada numeric,
  apontamentos_depositos text,
  observacoes text,
  atualizado_em timestamptz not null default now()
);
alter table contingency_atual enable row level security;
create policy "anon all" on contingency_atual for all to anon using (true) with check (true);
alter publication supabase_realtime add table contingency_atual;
